server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:2023/postgres

  jpa:
    hibernate:
      ddl-auto: update
